platform :ios,'12.2'
project './SimpleMobile.xcodeproj'
target 'SimpleMobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCGSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git", :tag => '1.2.0'
end
