platform :ios,'12.0'
project './TCRDemo.xcodeproj'
target 'TCRDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCRSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git"
end
