platform :ios,'12.2'
project './SwiftPCDemo.xcodeproj'
target 'SwiftPCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCGSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git", :tag => '1.1.9.1'
end
