platform :ios,'12.2'
project './simpleDemo.xcodeproj'
target 'simpleDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCRSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git", :tag => '2.1.8'
end
