platform :ios,'15.0'
project './TCAIDemo.xcodeproj'
target 'TCAIDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCRSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git", :tag => '3.17.0'
end
