platform :ios,'12.2'
project './vKeyDemo.xcodeproj'
target 'vKeyDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'TCRSDK', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git", :tag => '3.1.1'
  pod 'TCRVKey', :git => "https://github.com/tencentyun/cloudgame-ios-sdk.git"
end
